import os
Import('env')

include_paths = [os.path.join(env['lapkt'], 'include')]


if env['edebug']:
	lapkt_lib_sufix = '-edebug'
elif env['debug']:
	lapkt_lib_sufix = '-debug'
else:
	lapkt_lib_sufix = ''

lapkt2_libs = [
	'liblapkt-novelty' + lapkt_lib_sufix,
	'liblapkt' + lapkt_lib_sufix,
	'boost_timer',
	'boost_filesystem'
]

env.Append( CPPPATH = [ os.path.abspath(p) for p in include_paths ] )
env.Append( LIBS = lapkt2_libs)
env.Append( LIBPATH = [ os.path.abspath(os.path.join(env['lapkt'], 'lib'))] )
