
Import('env', 'suffix')
import os

include_paths = [ '.' ]

lib_name = 'agv_external{}'.format(suffix)

env.Append( CCFLAGS = '-fPIC' )
env.Append( LINKFLAGS = '-shared')
env.Append( LIBPATH = ['/usr/local/lib'])
env.Append( LIBS=[] )
env.Append(CPPPATH = [ os.path.abspath(p) for p in include_paths ])
env['STATIC_AND_SHARED_OBJECTS_ARE_THE_SAME']=1
sources = Glob('*.cxx')
objs = [ env.Object(src) for src in sources]

lib = env.SharedLibrary(lib_name, objs )
Return('lib')
