
import os
import util.build
Import('env', 'sources')

# Paths are relative to SConscript file directory
# Temporary HACK: Ignore files under src/modules directory
sources += [s for s in util.build.locate_source_files('../../src', '*.cxx') if "src/modules" not in s]
fs_include_paths = [os.path.join(env['fs'], 'src') ]

env.Append(CCFLAGS = ['-Wall', '-pedantic', '-std=c++14' ])  # Flags common to all options

if env['edebug']:
	env.Append( CCFLAGS = ['-g', '-DDEBUG', '-DEDEBUG' ] )
	env['fs_libname'] ='fs-edebug'
elif env['debug']:
	env.Append( CCFLAGS = ['-g', '-DDEBUG' ] )
	env['fs_libname'] ='fs-debug'
else:
	env.Append( CCFLAGS = ['-O3', '-DNDEBUG' ] )
	env['fs_libname'] ='fs'

fs_libs = ['boost_program_options', 'boost_serialization', 'boost_system', 'boost_timer', 'boost_chrono', 'rt', 'boost_filesystem', 'm']
fs_lib_paths = [ os.path.join(env['fs'], 'lib')]

env.Append( CPPPATH = [ os.path.abspath(p) for p in fs_include_paths ] )
env.Append( LIBS = fs_libs )
env.Append( LIBPATH = [ os.path.abspath(p) for p in fs_lib_paths ] )
